# Generated by Django 3.2 on 2021-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
